version: '3.1'
services:
  website:
    image: ghcr.io/getzola/zola:v0.16.0
    ports:
      - "8000:8000"
      - "1024:1024"
    working_dir: /app
    volumes:
      - ./website:/app
    command: "serve --interface 0.0.0.0 --port 8000 --base-url localhost"

  app:
    image: rust:latest
    volumes:
      - .:/app
    working_dir: /app
    command: cargo run
